# Stage 1 build
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN apk add --no-cache python3 make g++ build-base
RUN npm ci --silent
COPY . .
RUN npm run build

# Stage 2 runtime
FROM nginx:alpine AS runtime
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
