version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - posnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend:/app:delegated
    networks:
      - posnet
    command: ["npm","run","start"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: pos-all-frontend
    ports:
      - "8081:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:4000/api
    networks:
      - posnet

volumes:
  db-data:

networks:
  posnet:
    driver: bridge
