version: '3.9'

services:
  posall-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: pos
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: posdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pos -d posdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    env_file: ./backend/.env
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      posall-db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: sh -c "npm run migrate && npm run seed && npm run start"

  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    restart: unless-stopped
    ports:
      - "3000:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  db_data:
