version: "3.8"

services:
  nginx:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/ssl/certs:ro
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-/api}
    restart: unless-stopped
    expose:
      - "5173"
    networks:
      - webnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
