version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - posnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend:/app:delegated
    networks:
      - posnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:4000/api
    volumes:
      - ./frontend:/app:delegated
    networks:
      - posnet

volumes:
  db-data:

networks:
  posnet:
    driver: bridge

services:
  backend:
    build: ./backend
    command: ["npm","run","start"]
    ports:
      - "4000:4000"

