version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: pos
      POSTGRES_PASSWORD: pospass
      POSTGRES_DB: posdb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pos"]
      interval: 10s
      retries: 5

  backend:
    build: ./backend
    restart: always
    env_file: ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    restart: always
    env_file: ./frontend/.env
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app

volumes:
  db_data:
